apiVersion: v1
kind: Service
metadata:
  name: guestbook-backend
  namespace: sample-webapp2
spec:
  selector:
    app: guestbook
  ports:
    - port: 80          # Service port (HTTP)
      targetPort: 3000  # Container port where backend listens
      protocol: TCP
  type: ClusterIP       # No LoadBalancer needed, Ingress will handle external traffic
